# version is now using "compose spec"
# v2 and v3 are now combined!
# docker-compose v1.27+ required
version: "3"

services:
  mongo:
    container_name: mongo-db
    image: mongo:4.4.13
    volumes:
      - mongo-db:/data/db
      - mongo-config:/data/configdb
      - ./healthchecks:/healthchecks:ro
    healthcheck:
      test: [ "CMD", "sh", "healthchecks/mongo.sh" ]
      # check for 1 min before considered unhealthy
      interval: 3s
      retries: 20
    ports:
      - ${MONGO_DB_PORT}:${MONGO_DB_PORT}
    networks:
      - back-tier
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_DB_PORT: ${MONGO_DB_PORT}
    restart: unless-stopped # always

volumes:
  mongo-db:
      name: book-match_mongo-db
      external: true

  mongo-config:
      name: book-match_mongo-config

networks:
  back-tier:
